# Generated by Django 6.0.7 on 2026-08-04 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeronave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Cessna 152', max_length=100)),
                ('descricao_curta', models.CharField(help_text='Texto curto para aparecer no Card da frota', max_length=150)),
                ('imagem_principal', models.ImageField(help_text='Foto que aparece no Card', upload_to='frota/principais/')),
                ('historia', models.TextField(help_text='História e descrição longa (permite formatação)')),
                ('motor', models.CharField(help_text='Ex: Lycoming O-235-L2C', max_length=150)),
                ('capacidade', models.IntegerField(help_text='Número de lugares')),
                ('velocidade_cruzeiro', models.CharField(help_text='Ex: 107 nós', max_length=50)),
                ('autonomia', models.CharField(help_text='Ex: 4.5 horas', max_length=50)),
                ('ativo', models.BooleanField(default=True, help_text='Avião está ao serviço?')),
            ],
            options={
                'verbose_name': 'Aeronave',
                'verbose_name_plural': 'Frota',
            },
        ),
        migrations.CreateModel(
            name='ImagemAeronave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='frota/galeria/')),
                ('legenda', models.CharField(blank=True, max_length=100, null=True)),
                ('aeronave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='escola.aeronave')),
            ],
            options={
                'verbose_name': 'Imagem da Galeria',
                'verbose_name_plural': 'Galeria de Imagens',
            },
        ),
    ]
