# Generated by Django 6.0.7 on 2026-09-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeronave',
            name='link_externo',
            field=models.URLField(blank=True, help_text='Link para o site oficial do fabricante', max_length=500, null=True),
        ),
    ]
