# Generated by Django 6.0.7 on 2026-09-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_aeronave_link_externo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aeronave',
            options={'ordering': ['ordem'], 'verbose_name': 'Aeronave', 'verbose_name_plural': 'Frota'},
        ),
        migrations.AddField(
            model_name='aeronave',
            name='ordem',
            field=models.IntegerField(default=0, help_text='Ordem de apresentação (ex: 1 para aparecer primeiro)'),
        ),
    ]
