# Generated by Django 6.0.7 on 2026-09-19 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_alter_aeronave_options_aeronave_ordem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: ATPL', max_length=100)),
                ('horas_totais', models.CharField(help_text='Ex: 30 Hrs', max_length=50)),
                ('descricao_curta', models.TextField(help_text='Resumo que aparece no topo da página de cursos')),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='EtapaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_etapa', models.IntegerField(help_text='1, 2, 3... para ordenar a timeline')),
                ('titulo_etapa', models.CharField(help_text='Ex: Fase 1 - Ground School', max_length=150)),
                ('descricao', models.TextField(help_text='O que o aluno vai fazer nesta fase')),
                ('horas_associadas', models.CharField(blank=True, help_text='Ex: 920H Teoria', max_length=50, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='escola.curso')),
            ],
            options={
                'verbose_name': 'Etapa do Curso',
                'verbose_name_plural': 'Etapas do Curso',
                'ordering': ['numero_etapa'],
            },
        ),
    ]
