# Generated by Django 6.0.7 on 2026-09-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_curso_etapacurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='descricao_completa',
            field=models.TextField(blank=True, help_text='Texto detalhado da página do curso', null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='imagem_destaque',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/'),
        ),
        migrations.AddField(
            model_name='curso',
            name='saidas_profissionais',
            field=models.TextField(blank=True, help_text='O que o aluno pode fazer após o curso', null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
