# Generated by Django 6.0.7 on 2026-09-21 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0005_curso_descricao_completa_curso_imagem_destaque_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testemunho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(help_text='Ex: First Officer - Avião Comercial', max_length=100)),
                ('texto', models.TextField()),
                ('ativo', models.BooleanField(default=True, help_text='Desmarca para ocultar este testemunho temporariamente')),
                ('ordem', models.IntegerField(default=0)),
                ('curso', models.ForeignKey(help_text='A que curso pertence este testemunho?', on_delete=django.db.models.deletion.CASCADE, related_name='testemunhos', to='escola.curso')),
            ],
            options={
                'verbose_name': 'Testemunho',
                'verbose_name_plural': 'Testemunhos',
                'ordering': ['ordem'],
            },
        ),
    ]
