# Generated by Django 6.0.7 on 2026-09-22 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0006_testemunho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carreira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.CharField(help_text='Exemplo: ✈️, 🍸, 📦', max_length=50)),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('ordem', models.IntegerField(default=0)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreiras', to='escola.curso')),
            ],
            options={
                'verbose_name': 'Carreira / Saída Profissional',
                'verbose_name_plural': 'Carreiras / Saídas Profissionais',
                'ordering': ['ordem'],
            },
        ),
    ]
