# Generated by Django 6.0.7 on 2026-09-24 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0007_carreira'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recrutador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Recrutador (Email)',
                'verbose_name_plural': 'Recrutadores (Emails)',
            },
        ),
        migrations.CreateModel(
            name='TemplateEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(default='Nova Candidatura: {nome}', help_text='Usa {nome} e {curso} para personalizar o assunto.', max_length=200)),
                ('corpo_mensagem', models.TextField(default='Temos um novo candidato!\n\nNome: {nome}\nEmail: {email}\nTelefone: {telefone}\nCurso: {curso}\n\nMensagem do candidato:\n{mensagem}', help_text='Tags disponíveis: {nome}, {email}, {telefone}, {curso}, {mensagem}. Escreve o texto como preferires.')),
            ],
            options={
                'verbose_name': 'Template de Email',
                'verbose_name_plural': 'Template de Email',
            },
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('data_submissao', models.DateTimeField(auto_now_add=True)),
                ('curso_interesse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='escola.curso')),
            ],
            options={
                'verbose_name': 'Candidatura',
                'verbose_name_plural': 'Candidaturas',
                'ordering': ['-data_submissao'],
            },
        ),
    ]
